#!/usr/bin/env node
// Prepares the two inputs the design-sync converter needs from this repo.
// Run from the repo root: node .design-sync/prepare.mjs
//
// This repo is an application, not a published component library — there is no
// dist/ and no barrel — so both inputs are derived here rather than discovered:
//
//   1. frontend/.ds-cache/ds.css — the stylesheet cfg.cssEntry points at. It
//      lives under frontend/ because the converter bounds cssEntry to the
//      package dir and silently skips anything resolving outside it.
//      The Tailwind v4 CLI compiles .design-sync/tailwind-entry.css, which
//      imports the app's real frontend/src/index.css (tokens, @font-face, base
//      layer, keyframes) and adds @source directives so utilities the design
//      agent writes for its own layout glue resolve, not only the ones the app
//      happens to use. The PP Mori woff2s are mirrored next to the output
//      because Tailwind inlines the imported @font-face rules without
//      rewriting their url()s, which are relative to frontend/src/.
//
//   2. frontend/.ds-cache/mdi-react-shim.js + frontend/.ds-tsconfig.json — an
//      ESM interop shim for @mdi/react, aliased in via tsconfig paths (which
//      the converter's esbuild pass honors). @mdi/react is a webpack CJS
//      bundle, and frontend/package.json declares "type": "module", so esbuild
//      applies Node's ESM->CJS interop: `import Icon from '@mdi/react'` yields
//      the whole module namespace instead of the forwardRef, and React throws
//      "Element type is invalid". Vite papers over this with __esModule
//      interop, which is why the app itself works. The named export survives
//      the same interop intact, so the shim re-exports through it.
//      Affects CircleIconButton, CopyBtn and AccountLayout.
//
//   3. frontend/.ds-entry.jsx — the bundle entry cfg.entry points at. Named
//      re-exports of the scoped UI kit, so window.RCSTravels gets stable names
//      regardless of each file's default-export style. MemoryRouter rides along
//      because several components call useViewNavigate() and need a router in
//      context; cfg.provider names it as the preview wrapper.
import { execFileSync } from 'node:child_process';
import { cpSync, mkdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

// name → [module path relative to frontend/, export name or 'default']
export const KIT = {
  AccountLayout: ['src/components/ui/AccountLayout.jsx', 'default'],
  BackgroundPanel: ['src/components/ui/BackgroundPanel.jsx', 'default'],
  Button: ['src/components/ui/Button.jsx', 'default'],
  Chips: ['src/components/ui/Chips.tsx', 'default'],
  CircleIconButton: ['src/components/ui/CircleIconButton.jsx', 'default'],
  CopyBtn: ['src/components/ui/bookingDisplay.jsx', 'CopyBtn'],
  DateTimeSelector: ['src/components/ui/DateTimeSelector.jsx', 'DateTimeSelector'],
  EmptyState: ['src/components/ui/EmptyState.jsx', 'default'],
  SecondaryButton: ['src/components/ui/stateChrome.jsx', 'SecondaryButton'],
  ErrorPanel: ['src/components/ui/ErrorPanel.jsx', 'default'],
  FailureState: ['src/components/ui/FailureState.jsx', 'default'],
  Input: ['src/components/ui/Input.jsx', 'default'],
  NoticePill: ['src/components/ui/NoticePill.jsx', 'default'],
  RefreshNotice: ['src/components/ui/RefreshNotice.jsx', 'default'],
  RideCancelledToast: ['src/components/ui/RideCancelledToast.jsx', 'default'],
  RoutePanel: ['src/components/ui/RoutePanel.jsx', 'default'],
  SettingRow: ['src/components/ui/SettingRow.jsx', 'default'],
  Skeleton: ['src/components/ui/Skeleton.jsx', 'default'],
  Toggle: ['src/components/ui/Toggle.jsx', 'default'],
};

function buildCss() {
  const out = join(ROOT, 'frontend/.ds-cache/ds.css');
  mkdirSync(dirname(out), { recursive: true });
  execFileSync(
    process.execPath,
    [
      join(ROOT, '.ds-sync/node_modules/@tailwindcss/cli/dist/index.mjs'),
      '-i', join(ROOT, '.design-sync/tailwind-entry.css'),
      '-o', out,
    ],
    { cwd: ROOT, stdio: 'inherit' },
  );
  cpSync(join(ROOT, 'frontend/src/assets/fonts'), join(dirname(out), 'assets/fonts'), { recursive: true });
  console.log(`ds.css: ${(statSync(out).size / 1024).toFixed(1)} KB`);
}

function buildEntry() {
  const lines = [
    '// GENERATED by .design-sync/prepare.mjs — do not edit.',
    '// Bundle entry for the claude.ai/design import; not used by the app.',
    '',
    ...Object.entries(KIT).map(([name, [path, exp]]) =>
      exp === 'default'
        ? `export { default as ${name} } from './${path}';`
        : `export { ${exp} as ${name} } from './${path}';`,
    ),
    '',
    '// Router context for components that call useViewNavigate(). Named as',
    '// cfg.provider so every preview card renders inside it.',
    "export { MemoryRouter } from 'react-router-dom';",
    '',
  ];
  const out = join(ROOT, 'frontend/.ds-entry.jsx');
  writeFileSync(out, lines.join('\n'));
  console.log(`entry: ${Object.keys(KIT).length} components + MemoryRouter`);
}

// See note 2 in the header. `import * as ns` is deliberate: under Node interop
// esbuild produces a namespace whose `.default` is the CJS module.exports
// object, but whose named keys are copied through as the real values.
function buildMdiShim() {
  const dir = join(ROOT, 'frontend/.ds-cache');
  mkdirSync(dir, { recursive: true });
  writeFileSync(
    join(dir, 'mdi-react-shim.js'),
    [
      '// GENERATED by .design-sync/prepare.mjs — do not edit.',
      "// ESM interop shim for @mdi/react; see prepare.mjs header note 2.",
      "import * as ns from '@mdi/react/Icon.js';",
      '',
      'const cjs = ns.default && typeof ns.default === "object" ? ns.default : ns;',
      'const Icon = ns.Icon ?? cjs.Icon ?? cjs.default ?? cjs;',
      '',
      'export default Icon;',
      'export const Stack = ns.Stack ?? cjs.Stack;',
      '',
    ].join('\n'),
  );
  writeFileSync(
    join(ROOT, 'frontend/.ds-tsconfig.json'),
    JSON.stringify(
      {
        extends: './tsconfig.json',
        compilerOptions: {
          baseUrl: '.',
          paths: { '@mdi/react': ['./.ds-cache/mdi-react-shim.js'] },
        },
        include: ['src'],
      },
      null,
      2,
    ) + '\n',
  );
  console.log('shim: @mdi/react -> .ds-cache/mdi-react-shim.js');
}

buildCss();
buildMdiShim();
buildEntry();
