#!/usr/bin/env node
import fs from 'node:fs/promises'
import path from 'node:path'
import { scanProject, defaultRepoRoot } from './scan-project.mjs'

const checkOnly = process.argv.includes('--check')
const repoRoot = defaultRepoRoot()
const outputPath = path.join(repoRoot, 'tools/code-atlas/src/generated-atlas.js')

try {
  const atlasData = await scanProject(repoRoot)
  const errors = atlasData.diagnostics.filter(item => item.level === 'error')
  if (!checkOnly) {
    const moduleText = `// Generated by scripts/generate-atlas.mjs. Do not edit by hand.\nexport const atlasData = ${JSON.stringify(atlasData, null, 2)};\n`
    await fs.mkdir(path.dirname(outputPath), { recursive: true })
    await fs.writeFile(outputPath, moduleText, 'utf8')
  }
  const action = checkOnly ? 'validated' : 'generated'
  console.log(`Code Atlas ${action}: ${atlasData.nodes.length} nodes, ${atlasData.edges.length} edges, ${atlasData.diagnostics.length} diagnostics.`)
  if (errors.length) {
    for (const error of errors) console.error(`[${error.code}] ${error.message}`)
    process.exitCode = 1
  }
} catch (error) {
  console.error(`Code Atlas scan failed: ${error.stack || error.message}`)
  process.exitCode = 1
}
